### ISSUE TITLE
now2ms is millisecond, right?

### ISSUE THREAD

**Issue by leonlee** [knutin/edatetime#7]
Current impl:
now2ms({MegaSecs,Secs,MicroSecs}) ->
    (MegaSecs \* 1000000 + Secs) \* 1000000 + (MicroSecs div 1000).

should be:
now2ms({MegaSecs,Secs,MicroSecs}) ->
    (MegaSecs \* 1000000 + Secs) \* 1000+ (MicroSecs div 1000).

**Comment by knutin** [comment]
Sorry for taking some time to get back to you.

Yes, you're right. I've fixed this in 7274c0e. Thanks!
